In [1]:
import pandas as pd
import numpy as np

In [ ]:
# first row contains "Report Date"
df = pd.read_csv('data/UK-Sanctions-List.csv', skiprows=1)

C:\Users\44743\AppData\Local\Temp\ipykernel_9116\4095782856.py:1: DtypeWarning: Columns (0: IMO number, 1: Current owner/operator (s), 2: Previous owner/operator (s), 3: Current believed flag of ship, 4: Previous flags, 5: Type of ship) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('data/UK-Sanctions-List.csv', skiprows=1)

In [10]:
df.head()

,Last Updated,Unique ID,OFSI Group ID,UN Reference Number,Name 6,Name 1,Name 2,Name 3,Name 4,Name 5,...,IMO number,Current owner/operator (s),Previous owner/operator (s),Current believed flag of ship,Previous flags,Type of ship,Tonnage of ship,Length of ship,Year Built,Hull identification number (HIN)
0,16/04/2026,AFG0001,12703.0,TAe.010,HAJI KHAIRULLAH HAJI SATTAR MONEY EXCHANGE,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,16/04/2026,AFG0001,12703.0,TAe.010,HAJI KHAIRULLAH HAJI SATTAR MONEY EXCHANGE,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,16/04/2026,AFG0001,12703.0,TAe.010,HAJI KHAIRULLAH HAJI SATTAR MONEY EXCHANGE,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,16/04/2026,AFG0001,12703.0,TAe.010,HAJI KHAIRULLAH HAJI SATTAR MONEY EXCHANGE,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,16/04/2026,AFG0001,12703.0,TAe.010,HAJI KHAIRULLAH HAJI SATTAR MONEY EXCHANGE,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df.shape

(57387, 58)

In [13]:
df.describe()

,OFSI Group ID,Tonnage of ship,Length of ship,Year Built,Hull identification number (HIN)
count,54805.000000,402.000000,246.000000,676.000000,0.0
mean,12413.723638,31653.631841,110.513618,2000.585799,NaN
std,2538.523624,38325.080969,42.897142,10.524330,NaN
min,6894.000000,748.000000,58.000000,1973.000000,NaN
25%,11199.000000,3037.000000,85.000000,1995.000000,NaN
50%,12446.000000,6788.000000,98.000000,2004.000000,NaN
75%,13702.000000,60303.000000,116.000000,2007.000000,NaN
max,17285.000000,164565.000000,274.500000,2024.000000,NaN

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 57387 entries, 0 to 57386
Data columns (total 58 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Last Updated                                57387 non-null  str
 1   Unique ID                                   57387 non-null  str
 2   OFSI Group ID                               54805 non-null  float64
 3   UN Reference Number                         20532 non-null  str
 4   Name 6                                      57275 non-null  str
 5   Name 1                                      24088 non-null  str
 6   Name 2                                      12242 non-null  str
 7   Name 3                                      2583 non-null   str
 8   Name 4                                      480 non-null    str
 9   Name 5                                      101 non-null    str
 10  Name type                                   57323 non-null  str
 11  Alias strength                              12982 non-null  str
 12  Title                                       2462 non-null   str
 13  Name non-latin script                       7878 non-null   str
 14  Non-latin script type                       4044 non-null   str
 15  Non-latin script language                   3602 non-null   str
 16  Regime Name                                 57387 non-null  str
 17  Designation Type                            57387 non-null  str
 18  Designation source                          57387 non-null  str
 19  Sanctions Imposed                           57387 non-null  str
 20  Other Information                           51571 non-null  str
 21  UK Statement of Reasons                     57067 non-null  str
 22  Address Line 1                              32105 non-null  str
 23  Address Line 2                              20605 non-null  str
 24  Address Line 3                              12738 non-null  str
 25  Address Line 4                              5322 non-null   str
 26  Address Line 5                              7657 non-null   str
 27  Address Line 6                              37747 non-null  str
 28  Address Postal Code                         11064 non-null  str
 29  Address Country                             45245 non-null  str
 30  Phone number                                25115 non-null  str
 31  Website                                     19335 non-null  str
 32  Email address                               24196 non-null  str
 33  Date Designated                             57387 non-null  str
 34  D.O.B                                       24943 non-null  str
 35  Nationality(/ies)                           21990 non-null  str
 36  National Identifier number                  7062 non-null   str
 37  National Identifier additional information  6762 non-null   str
 38  Passport number                             10652 non-null  str
 39  Passport additional information             9469 non-null   str
 40  Position                                    15224 non-null  str
 41  Gender                                      10799 non-null  str
 42  Town of birth                               20525 non-null  str
 43  Country of birth                            22059 non-null  str
 44  Type of entity                              16129 non-null  str
 45  Subsidiaries                                5611 non-null   str
 46  Parent company                              7775 non-null   str
 47  Business registration number (s)            4501 non-null   str
 48  IMO number                                  855 non-null    str
 49  Current owner/operator (s)                  767 non-null    str
 50  Previous owner/operator (s)                 6 non-null      str
 51  Current believed flag of ship               725 non-null    str
 52  Previous flags                              242 non-null    str
 53  Type of ship                                602 non-null    str
 54  Tonnage of ship                             402 non-null    float64
 55  Length of ship                              246 non-null    float64
 56  Year Built                                  676 non-null    float64
 57  Hull identification number (HIN)            0 non-null      float64
dtypes: float64(5), str(53)
memory usage: 25.4 MB

In [15]:
df.isnull().sum()

Last Updated                                      0
Unique ID                                         0
OFSI Group ID                                  2582
UN Reference Number                           36855
Name 6                                          112
Name 1                                        33299
Name 2                                        45145
Name 3                                        54804
Name 4                                        56907
Name 5                                        57286
Name type                                        64
Alias strength                                44405
Title                                         54925
Name non-latin script                         49509
Non-latin script type                         53343
Non-latin script language                     53785
Regime Name                                       0
Designation Type                                  0
Designation source                                0
Sanctions Imposed                                 0
Other Information                              5816
UK Statement of Reasons                         320
Address Line 1                                25282
Address Line 2                                36782
Address Line 3                                44649
Address Line 4                                52065
Address Line 5                                49730
Address Line 6                                19640
Address Postal Code                           46323
Address Country                               12142
Phone number                                  32272
Website                                       38052
Email address                                 33191
Date Designated                                   0
D.O.B                                         32444
Nationality(/ies)                             35397
National Identifier number                    50325
National Identifier additional information    50625
Passport number                               46735
Passport additional information               47918
Position                                      42163
Gender                                        46588
Town of birth                                 36862
Country of birth                              35328
Type of entity                                41258
Subsidiaries                                  51776
Parent company                                49612
Business registration number (s)              52886
IMO number                                    56532
Current owner/operator (s)                    56620
Previous owner/operator (s)                   57381
Current believed flag of ship                 56662
Previous flags                                57145
Type of ship                                  56785
Tonnage of ship                               56985
Length of ship                                57141
Year Built                                    56711
Hull identification number (HIN)              57387
dtype: int64